[project]
name = "flowStudy"
version = "0.1.0"
description = "Thermodynamics and fluid flow utilities"
authors = [{ name="Votre Nom" }]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
